version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build:
    working_directory: ~/your_thing
    docker:
      - image: themattrix/tox
    steps:
      - checkout
      - run: tox

workflows:
  main:
    jobs:
      - build