version: 2.1

orbs:
  win: circleci/windows@2.2.0 # The Windows orb give you everything you need to start using the Windows executor.

jobs:
  job1:
    working_directory: ~/PyEEM
    executor: 
      name: win/default # executor type
      shell: powershell.exe
    steps:
      - checkout
      - run: tox
  job2:
    working_directory: ~/PyEEM
    docker:
      - image: themattrix/tox
    steps:
      - checkout
      - run: tox

workflows:
  main:
    jobs:
      - job1
      - job2