# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
import pyeem

sys.path.insert(0, os.path.abspath("../../"))

# -- Project information -----------------------------------------------------

project = "PyEEM"
copyright = "2020, Drew Meyers"
author = "Drew Meyers"

# The full version, including alpha/beta/rc tags
version = pyeem.__version__
release = version

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
# extensions = ["sphinx.ext.napoleon", "sphinx.ext.autodoc", "sphinx.ext.autosummary"]
extensions = ["sphinx_automodapi.automodapi"]
numpydoc_show_class_members = False

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
language = "en"
# spell checking
spelling_lang = "en_US"
spelling_word_list_filename = "spelling_wordlist.txt"
spelling_show_suggestions = True

# Options for HTML output
# Theme
try:
    # msmb_theme extends rtd_theme
    import msmb_theme
    import sphinx_rtd_theme

    html_theme_path = [
        msmb_theme.get_html_theme_path(),
        sphinx_rtd_theme.get_html_theme_path(),
    ]
    html_theme = "msmb_theme"
except ImportError:
    html_theme = "default"

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]
html_logo = "_static/pyeem.png"
