name: Documentation Build

on:
  push:
    paths:
      - "docs/**"
      - "README.md"
      - "CONTRIBUTING.md"
  pull_request:
    paths:
      - "docs/**"
      - "README.md"
      - "CONTRIBUTING.md"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -e .[docs]
      - name: Build documentation
        run: sphinx-build -a -b html -W docs/source/ docs/build/